apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana-provisioning-datasources
          configMap:
            name: grafana-provisioning-datasources
        - name: grafana-provisioning-dashboards
          configMap:
            name: grafana-provisioning-dashboards
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
        - name: sensu-client-defaults
          configMap:
            name: sensu-client-defaults
      containers:
        - name: grafana
          image: sensu/grafana:latest
          ports:
            - protocol: TCP
              containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: password
          volumeMounts:
            - name: grafana-provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
        - name: sensu-client
          image: sensu/sensu-classic:1.5.0-1
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SENSU_TRANSPORT_NAME
              value: "redis"
            - name: REDIS_URL
              value: "redis://$(SENSU_REDIS_SERVICE_HOST):$(SENSU_REDIS_SERVICE_PORT)/0"
            - name: RABBITMQ_URL
              value: "amqp://sensu:supersecret@$(SENSU_RABBITMQ_SERVICE_HOST):$(SENSU_RABBITMQ_SERVICE_PORT)/%2Fsensu"
            - name: SENSU_CLIENT_SUBSCRIPTIONS
              value: "sidecar,grafana"
          volumeMounts:
            - name: sensu-client-defaults
              mountPath: /etc/sensu/conf.d/
          ports:
            - containerPort: 3030
