---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: webui
      protocol: TCP
      port: 3001
      targetPort: 3000
  type: LoadBalancer
