---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - name: api
      protocol: TCP
      port: 8086
      targetPort: 8086
    - name: udp
      protocol: UDP
      port: 8089
      targetPort: 8089
