apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  template:
    metadata:
      name: influxdb
      labels:
        app: influxdb
    spec:
      volumes:
        - name: influxdb-config
          configMap:
            name: influxdb-config
        - name: sensu-client-defaults
          configMap:
            name: sensu-client-defaults
      containers:
        - name: influxdb
          image: influxdb:1.7.1
          ports:
            - protocol: TCP
              containerPort: 8086
            - protocol: UDP
              containerPort: 8089
          volumeMounts:
            - name: influxdb-config
              mountPath: /etc/influxdb
          env:
            - name: INFLUXDB_DB
              value: sensu
            - name: INFLUXDB_USER
              value: sensu
            - name: INFLUXDB_USER_PASSWORD
              value: password
        - name: sensu-client
          image: sensu/sensu-classic:1.5.0-1
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SENSU_TRANSPORT_NAME
              value: "redis"
            - name: REDIS_URL
              value: "redis://$(SENSU_REDIS_SERVICE_HOST):$(SENSU_REDIS_SERVICE_PORT)/0"
            - name: RABBITMQ_URL
              value: "amqp://sensu:supersecret@$(SENSU_RABBITMQ_SERVICE_HOST):$(SENSU_RABBITMQ_SERVICE_PORT)/%2Fsensu"
            - name: SENSU_CLIENT_SUBSCRIPTIONS
              value: "sidecar,influxdb"
          volumeMounts:
            - name: sensu-client-defaults
              mountPath: /etc/sensu/conf.d/
          ports:
            - containerPort: 3030
