apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sensu-client
  labels:
    name: sensu-client
spec:
  template:
    metadata:
      labels:
        name: sensu-client
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: sensu-client-defaults
        configMap:
          name: sensu-client-defaults
      containers:
      - name: sensu-client
        image: sensu/sensu-classic:1.5.0-1
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: SENSU_CLIENT_NAME
          value: "kube-node-$(HOST_IP)"
        - name: SENSU_TRANSPORT_NAME
          value: "redis"
        - name: REDIS_URL
          value: "redis://$(SENSU_REDIS_SERVICE_HOST):$(SENSU_REDIS_SERVICE_PORT)/0"
        - name: RABBITMQ_URL
          value: "amqp://sensu:supersecret@$(SENSU_RABBITMQ_SERVICE_HOST):$(SENSU_RABBITMQ_SERVICE_PORT)/%2Fsensu"
        - name: SENSU_CLIENT_SUBSCRIPTIONS
          value: "daemonset,roundrobin:daemonset"
        volumeMounts:
        - name: sensu-client-defaults
          mountPath: /etc/sensu/conf.d/
        ports:
        - containerPort: 3030
          hostPort: 3030
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
