apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy-backend
spec:
  replicas: 2
  template:
    metadata:
      name: dummy-backend
      labels:
        app: dummy-backend
    spec:
      volumes:
      - name: sensu-client-defaults
        configMap:
          name: sensu-client-defaults
      containers:
      - name: dummy-backend
        image: portertech/dummy:1.2.0
        ports:
        - protocol: TCP
          containerPort: 8080
      - name: sensu-client
        image: portertech/sensu-classic:daemonset
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: SENSU_TRANSPORT_NAME
          value: "redis"
        - name: REDIS_URL
          value: "redis://$(SENSU_REDIS_SERVICE_HOST):$(SENSU_REDIS_SERVICE_PORT)/0"
        - name: RABBITMQ_URL
          value: "amqp://sensu:supersecret@$(SENSU_RABBITMQ_SERVICE_HOST):$(SENSU_RABBITMQ_SERVICE_PORT)/%2Fsensu"
        - name: SENSU_CLIENT_SUBSCRIPTIONS
          value: "sidecar,dummy"
        volumeMounts:
        - name: sensu-client-defaults
          mountPath: /etc/sensu/conf.d/
        ports:
        - containerPort: 3030
