---
apiVersion: v1
kind: Service
metadata:
  name: network-device
spec:
  selector:
    app: network-device
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
