apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sensu-enterprise
  labels:
    app: sensu-enterprise
spec:
  selector:
    matchLabels:
      app: sensu-enterprise
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: sensu-enterprise
      annotations:
        sensu.io/update: "2"
    spec:
      volumes:
        - name: sensu-enterprise-defaults
          configMap:
            name: sensu-enterprise-defaults
            optional: true
        - name: sensu-enterprise-checks
          configMap:
            name: sensu-enterprise-checks
            optional: true
        - name: sensu-enterprise-handlers
          configMap:
            name: sensu-enterprise-handlers
            optional: true
        - name: sensu-enterprise-integrations
          configMap:
            name: sensu-enterprise-integrations
            optional: true
        - name: sensu-enterprise-contacts
          configMap:
            name: sensu-enterprise-contacts
            optional: true
      containers:
        - name: sensu-enterprise
          image: sensuhq/sensu-classic-enterprise-demo:3.2.2-1 # Private image - request access
          env:
            - name: SENSU_API_PORT
              value: "4567"
            - name: SENSU_TRANSPORT_NAME
              value: "redis"
            - name: REDIS_URL
              value: "redis://$(SENSU_REDIS_SERVICE_HOST):$(SENSU_REDIS_SERVICE_PORT)/0"
            - name: RABBITMQ_URL
              value: "amqp://sensu:supersecret@sensu-rabbitmq.default.svc.cluster.local:5672/%2Fsensu"
          volumeMounts:
            - name: sensu-enterprise-defaults
              mountPath: /etc/sensu/conf.d/server
            - name: sensu-enterprise-checks
              mountPath: /etc/sensu/conf.d/checks
            - name: sensu-enterprise-handlers
              mountPath: /etc/sensu/conf.d/handlers
            - name: sensu-enterprise-integrations
              mountPath: /etc/sensu/conf.d/integrations
            - name: sensu-enterprise-contacts
              mountPath: /etc/sensu/conf.d/contacts
          ports:
            - containerPort: 4567
          readinessProbe:
            httpGet:
              path: /health
              port: 4567
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 4567
            initialDelaySeconds: 180
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
      imagePullSecrets:
        - name: docker-registry-creds
