---
apiVersion: v1
kind: Service
metadata:
  name: sensu-enterprise
spec:
  selector:
    app: sensu-enterprise
  ports:
    - name: api
      protocol: TCP
      port: 4567
      targetPort: 4567
  type: LoadBalancer
