apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sensu-redis
  labels:
    app: sensu-redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensu-redis
  template:
    metadata:
      labels:
        app: sensu-redis
        role: master
    spec:
      containers:
        - name: sensu-redis-master
          image: redis:latest
          ports:
            - containerPort: 6379
